version: "3"

services:
  go-blog-app:
    container_name: go_blog_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    depends_on:
      - go-blog-postgres
    volumes:
      - ./:/blog
    networks:
      - go-blog-net

  go-blog-postgres:
    image: postgres:latest
    container_name: go_blog_app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=goblog
    volumes:
      - goblog_postgres:/var/lib/postgresql/data
    networks:
      - go-blog-net

volumes:
  goblog_postgres:

networks:
  go-blog-net:
    driver: bridge
