version: "3"

services:
  blog_app:
    container_name: go_blog_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      blog_db:
        condition: service_healthy
    volumes:
      - ./:/blog
    networks:
      - go-blog-net

  blog_db:
    image: postgres:13
    container_name: go_blog_app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=goblog
    volumes:
      - goblog_postgres:/var/lib/postgresql/data
    networks:
      - go-blog-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  blog_pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      blog_db:
        condition: service_healthy
    networks:
      - go-blog-net

volumes:
  goblog_postgres:

networks:
  go-blog-net:
    driver: bridge
